// Import the design system's machine-readable tokens into our normalized config.
// Usage: node scripts/import-tokens.mjs <path-to-netsecure-design>
// Re-run whenever the design system changes; tests then follow the real source of truth.
import fs from 'node:fs';
import path from 'node:path';

const dsPath = process.argv[2] || process.env.DS_PATH;
if (!dsPath) {
  console.error('Usage: node scripts/import-tokens.mjs <path-to-netsecure-design>');
  process.exit(2);
}
const read = (p) => JSON.parse(fs.readFileSync(path.join(dsPath, p), 'utf8'));
const t = read('agent/tokens.json');
const pkg = read('package.json');
const idx = read('agent/component.index.json');

const flat = JSON.stringify(t.button);
const heights = [...new Set([...flat.matchAll(/min-h-\[(\d+)px\]/g)].map((m) => Number(m[1])))].sort((a, b) => a - b);

// Radii: documented scale + brand signature radii (CSS vars) + Tailwind defaults (apps run on Tailwind v4).
const documented = t.radius.map((r) => r.px);
const signature = [...JSON.stringify(t.css).matchAll(/--nc-radius-\w+":\s*"(\d+)px/g)].map((m) => Number(m[1]));
const tailwindDefaults = [0, 2, 4, 6, 8, 12, 16, 24, 32];
const radiiPx = [...new Set([...documented, ...signature, ...tailwindDefaults])].sort((a, b) => a - b);

const fontNames = ['sans', 'display', 'mono'].map((k) => t.font[k].split(',')[0].replace(/['"]/g, '').trim());

// Every hex the design system itself defines (brand, status, surfaces, all theme presets).
// An inline color from this set may legitimately come from useTheme().primaryHex, so the runtime check allows it.
const allowedHex = [...new Set([t.brand, t.status, t.surface, t.primaryPalettes]
  .flatMap((o) => JSON.stringify(o).match(/#[0-9a-fA-F]{6}\b/g) || [])
  .map((h) => h.toLowerCase()))].sort();

const out = {
  _note: 'GENERATED by scripts/import-tokens.mjs from the design system repo. Do not edit by hand.',
  source: { package: pkg.name, version: pkg.version, file: 'agent/tokens.json' },
  brand: t.brand,
  status: Object.fromEntries(Object.entries(t.status).map(([k, v]) => [k, v.hex])),
  surface: { light: t.surface.light, dark: t.surface.dark },
  netos: {
    allowedFonts: fontNames,
    allowedHex,
    buttonHeightsPx: heights,
    smallButtonMaxHeightPx: 36,
    smallButtonMaxFontPx: 14,
    radiiPx,
    contrast: { normal: 4.5, large: 3 }
  },
  contracts: idx.contracts
};

fs.mkdirSync('config', { recursive: true });
fs.writeFileSync('config/tokens.json', JSON.stringify(out, null, 2) + '\n');
console.log(`Imported ${pkg.name}@${pkg.version}`);
console.log(`  fonts: ${fontNames.join(', ')}`);
console.log(`  button heights (px): ${heights.join(', ')}`);
console.log(`  radii (px): ${radiiPx.join(', ')}`);
